language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
os: linux
#virtualenv:
#  system_site_packages: true
install:
  - pip install -r requirements.txt
  - pip install cython

script:
  - pytest # or pytest for Python versions 3.6 and higher
after_success:
- coveralls