language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
#  - "3.7"
  - "3.7-dev"
os: linux
before_install:
  - sudo apt-get install -y libspatialite-dev

script:
  - ./ci.sh test

after_success:
- coveralls
- codecov
