language: python
language: python
python:
  - "3.6"
os: linux
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
  - pip install cython

script:
  - py.test # or pytest for Python versions 3.6 and higher
after_success:
- coveralls